### ISSUE TITLE
GCC 5.4.0 is not supported

### ISSUE THREAD

**Issue by laoshanxi** [libcpr/cpr#830]
Use ubuntu:16.04 docker container default compiler (gcc 5.4.0) can not pass build

build in ubuntu:16.04 docker container:
```
git clone --depth=1 -b 1.9.2 https://github.com/libcpr/cpr.git
cd cpr && mkdir build && cd build
cmake .. -DCPR_USE_SYSTEM_CURL=ON
cmake --build .
make install
```
```
bash-4.2# make
Consolidate compiler generated dependencies of target zlib
[ 17%] Built target zlib
Consolidate compiler generated dependencies of target libcurl
[ 89%] Built target libcurl
Consolidate compiler generated dependencies of target cpr
[ 90%] Building CXX object cpr/CMakeFiles/cpr.dir/auth.cpp.o
In file included from /data/b/cpr/cpr/auth.cpp:1:0:
/data/b/cpr/include/cpr/auth.h:20:21: error: function 'cpr::Authentication& cpr::Authentication::operator=(cpr::Authentication&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'cpr::Authentication& cpr::Authentication::operator=(cpr::Authentication&&)'
     Authentication& operator=(Authentication&& old) noexcept = default;
                     ^
In file included from /data/b/cpr/include/cpr/callback.h:4:0,
                 from /data/b/cpr/include/cpr/util.h:8,
                 from /data/b/cpr/cpr/auth.cpp:2:
/data/b/cpr/include/cpr/cprtypes.h: In instantiation of 'class cpr::StringHolder<cpr::Url>':
/data/b/cpr/include/cpr/cprtypes.h:106:20:   required from here
/data/b/cpr/include/cpr/cprtypes.h:33:19: error: function 'cpr::StringHolder<T>& cpr::StringHolder<T>::operator=(cpr::StringHolder<T>&&) [with T = cpr::Url]' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'cpr::StringHolder<cpr::Url>& cpr::StringHolder<cpr::Url>::operator=(cpr::StringHolder<cpr::Url>&&)'
     StringHolder& operator=(StringHolder&& old) noexcept = default;
                   ^
/data/b/cpr/include/cpr/cprtypes.h:121:10: error: function 'cpr::Url& cpr::Url::operator=(cpr::Url&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'cpr::Url& cpr::Url::operator=(cpr::Url&&)'
     Url& operator=(Url&& old) noexcept = default;
          ^
In file included from /data/b/cpr/include/cpr/cookies.h:4:0,
                 from /data/b/cpr/include/cpr/util.h:9,
                 from /data/b/cpr/cpr/auth.cpp:2:
/data/b/cpr/include/cpr/curlholder.h:31:45: error: missing initializer for member 'std::array<char, 256ul>::_M_elems' [-Werror=missing-field-initializers]
     std::array<char, CURL_ERROR_SIZE> error{};
                                             ^
cc1plus: all warnings being treated as errors
make[2]: *** [cpr/CMakeFiles/cpr.dir/auth.cpp.o] Error 1
make[1]: *** [cpr/CMakeFiles/cpr.dir/all] Error 2
make: *** [all] Error 2
```

**Is your feature request related to a problem? Please describe.**
Not new feature, just build failure.

**Describe the solution you'd like**
GCC 5.4.0 is better to support, but not important in nowadays.

**Describe alternatives you've considered**
I am also planning to deprecate compatibility of GCC version less than 7

**Additional context**
I am trying to use libcpr replace cpprestsdk in [app-mesh](https://github.com/laoshanxi/app-mesh) which looks out of maintenance now.

**Comment by COM8** [comment]
Thanks for reporting!
In theory [Allowing move constructors to throw [noexcept]](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2010/n3050.html) is a gcc 4.6 feature. 

```c++
/data/b/cpr/include/cpr/curlholder.h:31:45: error: missing initializer for member 'std::array<char, 256ul>::_M_elems' [-Werror=missing-field-initializers]
     std::array<char, CURL_ERROR_SIZE> error{};
```
can be solved via:
```c++
std::array<char, CURL_ERROR_SIZE> error{{}};
```

The other can be by removing the `noexcept` for older compilers.
Could you please try the following branch/commit: https://github.com/COM8/cpr/commit/3fa5f86c7b0d2f1d85fc36ff577db6d0e28f43de

**Comment by laoshanxi** [comment]
I tried but still failed:
```
docker run -ti --rm laoshanxi/appmesh:build_ubuntu16 bash
git clone https://github.com/COM8/cpr
cd cpr
git checkout 3fa5f86
mkdir build
cd build
cmake ..
make -j10
```

```
[ 90%] Building CXX object cpr/CMakeFiles/cpr.dir/session.cpp.o
In file included from /cpr/cpr/session.cpp:1:0:
/cpr/include/cpr/session.h:247:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Get()))> cpr::Session::GetCallback(Then)' does not match any in class 'cpr::Session'
 auto Session::GetCallback(Then then) -> std::future<decltype(then(Get()))> {
      ^
/cpr/include/cpr/session.h:183:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Get()))> cpr::Session::GetCallback(Then)
     auto GetCallback(Then then) -> std::future<decltype(then(Get()))>;
          ^
/cpr/include/cpr/session.h:253:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Post()))> cpr::Session::PostCallback(Then)' does not match any in class 'cpr::Session'
 auto Session::PostCallback(Then then) -> std::future<decltype(then(Post()))> {
      ^
/cpr/include/cpr/session.h:185:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Post()))> cpr::Session::PostCallback(Then)
     auto PostCallback(Then then) -> std::future<decltype(then(Post()))>;
          ^
/cpr/include/cpr/session.h:259:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Put()))> cpr::Session::PutCallback(Then)' does not match any in class 'cpr::Session'
 auto Session::PutCallback(Then then) -> std::future<decltype(then(Put()))> {
      ^
/cpr/include/cpr/session.h:187:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Put()))> cpr::Session::PutCallback(Then)
     auto PutCallback(Then then) -> std::future<decltype(then(Put()))>;
          ^
/cpr/include/cpr/session.h:265:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Head()))> cpr::Session::HeadCallback(Then)' does not match any in class 'cpr::Session'
 auto Session::HeadCallback(Then then) -> std::future<decltype(then(Head()))> {
      ^
/cpr/include/cpr/session.h:189:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Head()))> cpr::Session::HeadCallback(Then)
     auto HeadCallback(Then then) -> std::future<decltype(then(Head()))>;
          ^
/cpr/include/cpr/session.h:271:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Delete()))> cpr::Session::DeleteCallback(Then)' does not match any in class 'cpr::Session'
 auto Session::DeleteCallback(Then then) -> std::future<decltype(then(Delete()))> {
      ^
/cpr/include/cpr/session.h:191:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Delete()))> cpr::Session::DeleteCallback(Then)
     auto DeleteCallback(Then then) -> std::future<decltype(then(Delete()))>;
          ^
/cpr/include/cpr/session.h:277:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Options()))> cpr::Session::OptionsCallback(Then)' does not match any in class 'cpr::Session'
 auto Session::OptionsCallback(Then then) -> std::future<decltype(then(Options()))> {
      ^
/cpr/include/cpr/session.h:193:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Options()))> cpr::Session::OptionsCallback(Then)
     auto OptionsCallback(Then then) -> std::future<decltype(then(Options()))>;
          ^
/cpr/include/cpr/session.h:283:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Patch()))> cpr::Session::PatchCallback(Then)' does not match any in class 'cpr::Session'
 auto Session::PatchCallback(Then then) -> std::future<decltype(then(Patch()))> {
      ^
/cpr/include/cpr/session.h:195:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Patch()))> cpr::Session::PatchCallback(Then)
     auto PatchCallback(Then then) -> std::future<decltype(then(Patch()))>;
          ^
cpr/CMakeFiles/cpr.dir/build.make:285: recipe for target 'cpr/CMakeFiles/cpr.dir/session.cpp.o' failed
make[2]: *** [cpr/CMakeFiles/cpr.dir/session.cpp.o] Error 1
CMakeFiles/Makefile2:245: recipe for target 'cpr/CMakeFiles/cpr.dir/all' failed
make[1]: *** [cpr/CMakeFiles/cpr.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

```

```
root@bd6a25bf6372:/cpr/build# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
```

**Comment by COM8** [comment]
Aha, new errors 😄 .
But those are not fixable for such an old gcc compiler.

**Comment by laoshanxi** [comment]
Never mind, old compiler is not important to me ^^

**Comment by COM8** [comment]
ACK, then I'm going to close this issue.

**Comment by tplusy** [comment]
> I tried gcc5.4, but still failed:
> 
> docker run -ti --rm laoshanxi/appmesh:build_ubuntu16 bash
> git clone https://github.com/COM8/cpr
> cd cpr
> git checkout 3fa5f86
> mkdir build
> cd build
> cmake ..
> make -j10
> [ 90%] Building CXX object cpr/CMakeFiles/cpr.dir/session.cpp.o
> In file included from /cpr/cpr/session.cpp:1:0:
> /cpr/include/cpr/session.h:247:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Get()))> cpr::Session::GetCallback(Then)' does not match any in class 'cpr::Session'
>  auto Session::GetCallback(Then then) -> std::future<decltype(then(Get()))> {
>       ^
> /cpr/include/cpr/session.h:183:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Get()))> cpr::Session::GetCallback(Then)
>      auto GetCallback(Then then) -> std::future<decltype(then(Get()))>;
>           ^
> /cpr/include/cpr/session.h:253:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Post()))> cpr::Session::PostCallback(Then)' does not match any in class 'cpr::Session'
>  auto Session::PostCallback(Then then) -> std::future<decltype(then(Post()))> {
>       ^
> /cpr/include/cpr/session.h:185:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Post()))> cpr::Session::PostCallback(Then)
>      auto PostCallback(Then then) -> std::future<decltype(then(Post()))>;
>           ^
> /cpr/include/cpr/session.h:259:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Put()))> cpr::Session::PutCallback(Then)' does not match any in class 'cpr::Session'
>  auto Session::PutCallback(Then then) -> std::future<decltype(then(Put()))> {
>       ^
> /cpr/include/cpr/session.h:187:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Put()))> cpr::Session::PutCallback(Then)
>      auto PutCallback(Then then) -> std::future<decltype(then(Put()))>;
>           ^
> /cpr/include/cpr/session.h:265:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Head()))> cpr::Session::HeadCallback(Then)' does not match any in class 'cpr::Session'
>  auto Session::HeadCallback(Then then) -> std::future<decltype(then(Head()))> {
>       ^
> /cpr/include/cpr/session.h:189:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Head()))> cpr::Session::HeadCallback(Then)
>      auto HeadCallback(Then then) -> std::future<decltype(then(Head()))>;
>           ^
> /cpr/include/cpr/session.h:271:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Delete()))> cpr::Session::DeleteCallback(Then)' does not match any in class 'cpr::Session'
>  auto Session::DeleteCallback(Then then) -> std::future<decltype(then(Delete()))> {
>       ^
> /cpr/include/cpr/session.h:191:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Delete()))> cpr::Session::DeleteCallback(Then)
>      auto DeleteCallback(Then then) -> std::future<decltype(then(Delete()))>;
>           ^
> /cpr/include/cpr/session.h:277:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Options()))> cpr::Session::OptionsCallback(Then)' does not match any in class 'cpr::Session'
>  auto Session::OptionsCallback(Then then) -> std::future<decltype(then(Options()))> {
>       ^
> /cpr/include/cpr/session.h:193:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Options()))> cpr::Session::OptionsCallback(Then)
>      auto OptionsCallback(Then then) -> std::future<decltype(then(Options()))>;
>           ^
> /cpr/include/cpr/session.h:283:6: error: prototype for 'std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Patch()))> cpr::Session::PatchCallback(Then)' does not match any in class 'cpr::Session'
>  auto Session::PatchCallback(Then then) -> std::future<decltype(then(Patch()))> {
>       ^
> /cpr/include/cpr/session.h:195:10: error: candidate is: template<class Then> std::future<decltype (then(((cpr::Session*)this)->cpr::Session::Patch()))> cpr::Session::PatchCallback(Then)
>      auto PatchCallback(Then then) -> std::future<decltype(then(Patch()))>;
>           ^
> cpr/CMakeFiles/cpr.dir/build.make:285: recipe for target 'cpr/CMakeFiles/cpr.dir/session.cpp.o' failed
> make[2]: *** [cpr/CMakeFiles/cpr.dir/session.cpp.o] Error 1
> CMakeFiles/Makefile2:245: recipe for target 'cpr/CMakeFiles/cpr.dir/all' failed
> make[1]: *** [cpr/CMakeFiles/cpr.dir/all] Error 2
> Makefile:135: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> root@bd6a25bf6372:/cpr/build# gcc -v
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
> ```



> Aha, new errors 😄 . But those are not fixable for such an old gcc compiler.

Move the api define to class inner can fix this issues。

   template <typename Then>
    auto GetCallback(Then then) -> std::future<decltype(then(Get()))> {
        auto shared_this = GetSharedPtrFromThis();
        return async([shared_this](Then then_inner) { return then_inner(shared_this->Get()); }, std::move(then));
    }
