### ISSUE TITLE
cpr::GetCallback linkage fails with cpr 1.8.3

### ISSUE THREAD

**Issue by kdidkovsky** [libcpr/cpr#768]
When  cpr::GetCallback is used in cpr 1.8.3, linking fails. In 1.7.2 it's working fine.

## Description

I've written a program that uses cpr:

`void myClass::sendRequest(QString url, QJsonObject request, Callback callback) {
  cpr::GetCallback(callback, cpr::Url{url.toStdString()}, cpr::Body(stringify(request)), cpr::Timeout(timeoutMs));
}`

Where Callback is defined as following:

`using Callback = std::function<void(cpr::Response r)>;`

It was compiling and linking fine with cpr 1.7.2, but after an update of cpr to 1.8.3, the linkage began fo fail.

## Expected Behavior

Compilation and linkage should pass with 1.8.3 as they did with 1.7.2.

## Actual Behavior

I get the following error message from the linker:

> undefined reference to `cpr::GlobalThreadPool::GetInstance()'
> in function `std::future<decltype ({parm#1}({parm#2}...))> cpr::ThreadPool::Submit<cpr::GetCallback<std::function<void (cpr::Response)>, cpr::Url, cpr::Body, cpr::Timeout>(std::function<void (cpr::Response)>, cpr::Url, cpr::Body, cpr::Timeout)::{lambda(std::function<void (cpr::Response)>, cpr::Url, cpr::Body, cpr::Timeout)#1}, std::function<void (cpr::Response)>, cpr::Url, cpr::Body, cpr::Timeout>(cpr::GetCallback<std::function<void (cpr::Response)>, cpr::Url, cpr::Body, cpr::Timeout>(std::function<void (cpr::Response)>, cpr::Url, cpr::Body, cpr::Timeout)::{lambda(std::function<void (cpr::Response)>, cpr::Url, cpr::Body, cpr::Timeout)#1}&&, std::function<void (cpr::Response)>&&, cpr::Url&&, cpr::Body&&, cpr::Timeout&&)':
> myclass.cpp:(.text._ZN3cpr10ThreadPool6SubmitIZNS_11GetCallbackISt8functionIFvNS_8ResponseEEEJNS_3UrlENS_4BodyENS_7TimeoutEEEESt6futureIDTclfp_cl3Getspcl4movefp0_EEEEET_DpT0_EUlS6_S7_S8_S9_E_JS6_S7_S8_S9_EEESA_IDTclfp_spfp0_EEEOSD_DpOSE_[_ZN3cpr10ThreadPool6SubmitIZNS_11GetCallbackISt8functionIFvNS_8ResponseEEEJNS_3UrlENS_4BodyENS_7TimeoutEEEESt6futureIDTclfp_cl3Getspcl4movefp0_EEEEET_DpT0_EUlS6_S7_S8_S9_E_JS6_S7_S8_S9_EEESA_IDTclfp_spfp0_EEEOSD_DpOSE_]+0x542): undefined reference to `cpr::ThreadPool::CreateThread()'
> 
> /usr/bin/ld: myclass.cpp:(.text._ZN3cpr10ThreadPool6SubmitIZNS_11GetCallbackISt8functionIFvNS_8ResponseEEEJNS_3UrlENS_4BodyENS_7TimeoutEEEESt6futureIDTclfp_cl3Getspcl4movefp0_EEEEET_DpT0_EUlS6_S7_S8_S9_E_JS6_S7_S8_S9_EEESA_IDTclfp_spfp0_EEEOSD_DpOSE_[_ZN3cpr10ThreadPool6SubmitIZNS_11GetCallbackISt8functionIFvNS_8ResponseEEEJNS_3UrlENS_4BodyENS_7TimeoutEEEESt6futureIDTclfp_cl3Getspcl4movefp0_EEEEET_DpT0_EUlS6_S7_S8_S9_E_JS6_S7_S8_S9_EEESA_IDTclfp_spfp0_EEEOSD_DpOSE_]+0x556): undefined reference to `cpr::ThreadPool::Start(unsigned long)'`

## Steps to Reproduce

I've returned my system to cpr 1.7.2 so I'm unable to reproduce the error. But I think that the way to do so should be quite straightforward

1. Send a GetCallback request via cpr with four parameters: callback, URL, body and timeout, the callback should be a std::function<void(cpr::Response r)>
2. Try to compile the code.
3. The linker is supposed to complain

## Context

Yep, I know that sending GET requests with a body is not quite according to the standard. The problem is that it's the behavior of the system I have to interact with, and that's the reason I came to using cpr in the first place. If I didn't have to send such requests I would use QNetworkAccessManager as the software I'm writing uses Qt anyway, but there aren't many libraries allowing to send GET with a body, and cpr is one of them.

## Your Environment

* Version used: 1.8.3
* Where did you get it from (e.g. conan, vcpkg, master, ...): built from sources from Github. I've checked both openssl build and the one with SSL support disabled.
* Operating System and version: Linux Mint 20.3, g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, clang version 10.0.0-4ubuntu1 
* Link to a small example:

**Comment by COM8** [comment]
Turns out callback test are generally broken on newer versions of gcc. I will have a look at it.

**Comment by KingKili** [comment]
Weird, on my system (gcc 12.1.1) callback test compile and run just fine

**Comment by COM8** [comment]
This issue got introduced with #734.
@ithewei do you know anything about this.

The current state is, if I run all test successfully inside a [Fedora toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/), but outside of it, it does not work - at least for me.

**Comment by COM8** [comment]
@kdidkovsky fixed it on my side by removing the installed version of cpr from my system. From an earlier test run I had cpr installed on my system. Then when I compiled and run the tests from the repo it took the headers from the repo, but used the system lib file.
Please try the following:
```bash
sudo rm /usr/local/lib64/libcpr.*
sudo rm -rf /usr/local/include/cpr/
```

**Comment by COM8** [comment]
@kdidkovsky any updates from your side?

**Comment by COM8** [comment]
Hmmm. Once I've fixed the version clash on my system, it started working perfectly again. Are you sure there is no clash on your system where you are building with a more recent version, than you are using during execution?

Could you please provide a minimal example, so I can try reproducing this?

**Comment by COM8** [comment]
Pushing this back to a 1.9.x release.

**Comment by kdidkovsky** [comment]
> Could you please provide a minimal example, so I can try reproducing this?

I'm trying to reproduce the error as a minimal example, but I haven't succeeded yet. I'm running cpr::GetCallback from a timerEvent of a QObject's child, but in a separate example everything works fine. I'll send an example as soon as I'm able to reproduce the error.

**Comment by COM8** [comment]
Closing this one for now since it seams to be resolved.
